version: '3.8'
services:
  app:
    build: .
    image: backend
    restart: always
    container_name: back
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
